### ISSUE TITLE
Not accessible with the keyboard

### ISSUE THREAD

**Issue by yatil** [mnmly/select-switch#2]
This implementation destroys the default accessibility of the select element, without replacing it properly. Keyboard users aren’t able to operate the control at all, as display:none; on the select means it isn’t there for them to tab into or, alternatively the button (which should probably be a button element to be reachable by keyboard) has to be enhanced through Javascript to work properly.

**Comment by cadavre** [comment]
Please refer to http://www.w3.org/TR/wai-aria/

**Comment by yatil** [comment]
Stale
